### PR TITLE
fix(config_parser): Gracefully handle BOM

### LINKED ISSUE #2075: Key name '﻿<feff>;' is empty or contains forbidden characters.
## Describe the issue
I built polybar right after forking and cloning the repo. Now it doesn't start and in the log says [read below].

**Expected behavior:**
Polybar should start.

**Actual behavior:**
Polybar doesn't start.

**Was it working before?**
I downloaded, some days ago, the latest release (with sha256sum: `4d22c977969a561f561fdc7a609073854d8fea8a9eec6941e12a80457edcb63a`) and building with that it was working.
Also with the AUR stable version (the one I use daily) it was working.

## To Reproduce
Clone the repo with `git clone --recursive https://github.com/polybar/polybar`, and build with:
```bash
mkdir build
cd build
cmake ..
make -j$(nproc)
# Optional. This will install the polybar executable in /usr/local/bin
sudo make install
```
(from the wiki)

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
---
polybar|notice:  Parsing config file: /home/koraynilay/.config/polybar/config
polybar|error: /home/koraynilay/.config/polybar/config:1: Key name '<feff>﻿;' is empty or contains forbidden characters.
---
```

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`: 

```
polybar 3.4.0-96-gfc42da8-dev

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: 
```

## Additional context
I did a bit of research, and 0xFEFF is the [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark). So there could be a problem while reading the encoding.

### PR DESCRIPTION
**Pull request by parmort**
Closes #2075

Add a check to handle the byte order mark.

### CODE REVIEW

File: src/components/config_parser.cpp [hunk 1]
```diff
@@ -193,12 +193,16 @@ line_type config_parser::get_line_type(const string& line) {
     case '#':
       return line_type::COMMENT;
 
-    default:
+    default: {
+      if (string_util::contains(line, "﻿"))
```
Comment (patrick96) [inline src/components/config_parser.cpp:197]: This will not detect the BOM in header or comment lines. A better place to put this check would be at the beginning of the `parse_line` method.

Please also don't put a literal BOM here because this looks like an empty string on github and probably many editors (BOM inside the text signifies a zero-width nonbreaking space). It's probably best to put a string constant that is constructed from a `char` array in the header file.

File: src/components/config_parser.cpp [hunk 2]
```diff
@@ -193,12 +193,16 @@ line_type config_parser::get_line_type(const string& line) {
...
+        throw syntax_error("The file encoding is not supported. Please use UTF-8");
```
Comment (patrick96) [inline src/components/config_parser.cpp:198]: I think we should make this more specific. Since we only test for the UTF-8 encoding of the BOM, something like `This config file uses UTF-8 with BOM, which is not supported. Please use plain UTF-8 without BOM.` would make it clearer.

File: src/components/config_parser.cpp (hunk 1 above)
Comment (parmort) [reply src/components/config_parser.cpp]: I added the unit test and moved the check in dd65b76. I kept getting this redefined error when I tried to extract the BOM reference to a string constant in the `config_parser.hpp` file, I assume that somewhere the file is being loaded twice.

File: src/components/config_parser.cpp (hunk 2 above)
Comment (parmort) [reply src/components/config_parser.cpp]: Fixed in dd65b76
