### PR TITLE
feat(github): offline label & fixes

### LINKED ISSUE #1815: Github module displays label when offline
## Describe the issue
When offline the github module displays regardless of `empty-notifications = false`. 

**Expected behavior:**

The module either displays only when the last query resulted in a non-zero number of notifications or does not display even when offline (alternatively, allows for a custom offline label to be set).

**Actual behavior:**

Github module always displays when offline.

**Was it working before?**

Same behavior since I've first used github module (~3 weeks).

* Did you also experience this bug in an earlier version of polybar?

Yes.

* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
background = #222
background-alt = #444
foreground = #dfdfdf
foreground-alt = #888
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/main]
monitor = ${env:MONITOR:eDP-1}
width = 100%
height = 2.5%
radius = 6.0
fixed-center = false
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0
line-size = 2
padding = 1
module-margin = 1

font-0 = "Noto Sans Mono:size=10;1"
font-1 = "Noto Sans Mono:size=10;1"
font-2 = "Noto Sans Symbols:size=10;1"
font-3 = "Noto Sans Symbols2:size=10;1"

modules-left = 
modules-center =
modules-right = github

tray-position = right
tray-padding = 2
tray-maxsize = 24

[global/wm]
margin-top = 0

[module/github]
type = internal/github
token = ${file:~/.config/github/notifications.token}
empty-notifications = false
;label = %{u#ff9900 +u} %notifications% %{u-}
label = %{u#0099ff +u} 📫 %{u-}
interval = 10

[settings]
screenchange-reload = true

; vim:ft=dosini

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

Disconnect any internet connection.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: module/github: cannot complete the request to github: Couldn't connect to server
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
With full config:
* Online (No notifications):
2019-06-17-165021_1919x23_scrot
* Offline:
2019-06-17-165110_1919x22_scrot
## Environment:
* WM: xmonad 0.15-12
* Distro: Arch Linux
* Output of `polybar -vvv`:

polybar 3.3.1

Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

## Additional context
*Add any other context that you think is necessary about the problem here.*
Appears to occur as a result of drawing whenever the condition in line 81 of github.cpp is met (`0 != notifications || m_empty_notifications`), in conjunction with the choice to return `-1` from `get_number_of_notifications` when a non 200 http response is received and passing that directly to `update_label`.

### PR DESCRIPTION
**Pull request by kopecs**
Fixes #1815.

Should resolve the segfault issue with #910. The defaults are such that if offline the module displays `Offline` instead of the current `Notifications: -1`. Notifications are still set to -1 and a flag is set to indicate online/offline status which causes `format-offline` to be used when offline.

I haven't tested exhaustively but everything seemed to be working with a couple different configs on my machine.

MAINTAINER EDIT:
Closes #910

### CODE REVIEW

File: include/modules/github.hpp [hunk 1]
```diff
@@ -16,17 +16,23 @@ namespace modules {
...
     static constexpr auto TAG_LABEL = "<label>";
+    static constexpr auto TAG_LABEL_OFFLINE = "<label-offline>";
+    static constexpr auto FORMAT_OFFLINE = "format-offline";
 
     label_t m_label{};
+    label_t m_label_offline{};
     string m_accesstoken{};
     unique_ptr<http_downloader> m_http{};
     bool m_empty_notifications{false};
+    bool m_offline{false};
```
Comment (Lomadriel) [inline include/modules/github.hpp]:
```suggestion
    std::atomic<bool> m_offline{false};
```
Since this variable is accessed from the thread of the module and the main thread, it must be protected to avoid some problems.

**Comment by patrick96** [comment]
Thanks for reviewing @Lomadriel. I think we should stay with `format` and `label` since those represent the default state. Having `"Offline"` as the default should be fine. Though mpd actually has a default of `""` for `format-offline`, so you only need to set `label-offline` when you set `format-offline`, I think that is counter intuitive so this approach here seems better since it gives sane defaults.

File: src/modules/github.cpp [hunk 2]
```diff
@@ -24,9 +24,15 @@ namespace modules {
...
+    }
+
+    m_formatter->add(FORMAT_OFFLINE, TAG_LABEL_OFFLINE, {TAG_LABEL_OFFLINE});
 
-      update_label(0);
+    if (m_formatter->has(TAG_LABEL_OFFLINE)) {
+      m_label_offline = load_optional_label(m_conf, name(), TAG_LABEL_OFFLINE, "Offline");
     }
+
+    update_label(0);
```
Comment (Lomadriel) [inline src/modules/github.cpp]: I'm not sure if we should keep this line.
Indeed it prevents to display the label without applying the data but this isn't done in any module.
Maybe, we should address this globally rather that adding quick fixes in every modules.

Comment (kopecs) [reply src/modules/github.cpp]: As that was already the case, perhaps this isn't the best pr to address changing it in? Other than that the issues you noted should be fixed.

Comment (Lomadriel) [reply src/modules/github.cpp]: I think we can let this line for now. When I'll post a PR that solves these issues I'll remove it.

File: src/modules/github.cpp [hunk 3]
```diff
@@ -64,9 +70,12 @@ namespace modules {
       content = request();
     } catch (application_error& e) {
       m_log.warn("%s: cannot complete the request to github: %s", name(), e.what());
```
Comment (Lomadriel) [inline src/modules/github.cpp]: I didn't think about that before, but since "offline" is now a normal state, maybe we should replace this line by:
```suggestion
      m_log.info("%s: cannot complete the request to github: %s", name(), e.what());
```

What do you think of that @patrick96?

**Comment by kopecs** [comment]
Any more steps we need to take to get this merged?

**Comment by Lomadriel** [comment]
> Any more steps we need to take to get this merged?

This PR will be merged soon but the core team is a little busy.
I think your PR will be integrated into the 3.5.0 since we have already started to package the 3.4.0.

**Comment by kopecs** [comment]
Sounds good! Thanks for the update!

**Comment by Lomadriel** [comment]
Hello, one of my PR (#1841) just get merged and it introduced a conflict with yours.
Can I ask you to resolve it?

**Comment by kopecs** [comment]
Can you confirm that change resolves any conflict? It looks like we just both added a new member in the same place.

**Comment by Lomadriel** [comment]
Looks fine, that was the only conflict.
Thanks !

File: src/modules/github.cpp (hunk 3 above)
Comment (patrick96) [reply src/modules/github.cpp]: Good idea, we don't want to spam users with warnings that aren't really warnings.

File: src/modules/github.cpp [hunk 4]
```diff
@@ -69,9 +75,12 @@ namespace modules {
...
```
Comment (patrick96) [inline src/modules/github.cpp]:
```suggestion
      m_log.info("%s: cannot complete the request to github: %s", name(), e.what());
```

Comment (kopecs) [reply src/modules/github.cpp]: Resolved in cb83b83

**Comment by kopecs** [comment]
Best I can tell the segfault occurs as a result of attempting to clear the label in `update_label` when the `format` property is of certain (invalid?) format, e.g., text without any labels. Is there documentation on the grammar of the `format` property besides the description [here](https://github.com/polybar/polybar/wiki/Formatting)? I'm not totally sure what the resolution here should be; if `m_label` is a `nullptr` should I just immediately return from `update_label` with a warning, or is another solution preferred?

**Comment by patrick96** [comment]
Oh that segfault isn't even a result of your PR, but was there from the beginning. In other modules we always first check if a label is valid before dereferencing it, for example in the cpu module:

https://github.com/polybar/polybar/blob/4ef2bd55751591026183ad44a4e9cf5bd9484392/src/modules/cpu.cpp#L69-L78

We shouldn't print a warning since not having a label is completely valid (though not really useful)

As far as I can tell you only need to update `update_label`. However, this isn't really a bug in your PR, so we can also just merge this as-is.

We don't really have any developer documentation on the formats. But a format can contain an arbitrary string. Occurences of certain label, ramp, bar, animation names inside angle brackets (`<`, `>`) are treated as referencing the contents of that label, ramp etc. So `format = foo` is just as valid as `format = foo <label> bar` or just `format = <label>`.

> As an additional note, I'm assuming any build issues currently present are a result of google/googletest#2678.

Yes, the test build fails because of that. It's fixed on master.

**Comment by kopecs** [comment]
@patrick96 I've made the requested change about the logging level. I also added checks to confirm there aren't any `nullptr` dereferences (although if you'd prefer those are fixed separately I can roll it back). Is there any more action to be take at the moment?

**Comment by kopecs** [comment]
Yeah, the most recent revision should be sufficient. I just looked at it again today and I can't think of any reason I'd need to do that and it seems fine without.

> Because I would have thought checking if `m_label` is null and directly returning at the start of `update_label` would be enough.

In this case wouldn't I still need to check `m_offline_label`, or if one is non-null are they both set? I'm not totally clear on what holds with the label setinigs.

**Comment by patrick96** [comment]
> In this case wouldn't I still need to check m_offline_label

You only need to check `m_offline_label` before you dereference it. And there is no need to call `reset_tokens` on `m_offline_label` because it doesn't have any tokens. So you never derference it. You pass it to the builder though, but there the builder does its own checks.

**Comment by kopecs** [comment]
The most recent commit shouldn't have any `NULL` dereferences and doesn't clear tokens for things that don't have them.

File: src/modules/github.cpp [hunk 5]
```diff
@@ -68,10 +74,13 @@ namespace modules {
     try {
       content = request();
     } catch (application_error& e) {
-      m_log.warn("%s: cannot complete the request to github: %s", name(), e.what());
+      m_log.info("%s: cannot complete the request to github: %s", name(), e.what());
```
Comment (patrick96) [inline src/modules/github.cpp]:
```suggestion
      if (!m_offline) {
        m_log.info("%s: cannot complete the request to github: %s", name(), e.what());
      }
```

I think we should only show the message when we are no longer online, otherwise it would spam the logs for offline users.

**Comment by kopecs** [comment]
No problem! Nit picks appreciated.

**Comment by kopecs** [comment]
Let me know if there's still an issue with merging; I pulled master into this branch and it seemed to resolve it fine but I hadn't and don't see anywhere on github where it's indicating issues with merging to me (modulo that fact that I have changes requested).

**Comment by patrick96** [comment]
This is starting to make me mad. Now there is a merge conflict agian :angry:

**Comment by patrick96** [comment]
Not even cherry-picking the individual commits in this PR worked. I have now taken the diff of this entire PR and just applied it to our master branch and just force pushed. I have also noticed that we missed something: When empty-notifications is false, the label is supposed to be empty if there are no notifications, but this PR removed the call to `clear`, if have also fixed this.

**Comment by kopecs** [comment]
Sorry that this was such a headache to get done. Thanks for the update!
