### PR TITLE
fix: don't restart if zero active screens are reported

### LINKED ISSUE #2418: Polybar crashes when the system wakes up from sleep
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

Polybar disappears whenever the system wakes up from sleep. I have to start it manually every time I sleep my laptop.
**Expected behavior:**

Polybar works as it is before system sleeps.

**Actual behavior:**

Polybar exits or crashes.

**Was it working before?**
Yes. It works seamlessly before. The behavior came up after I upgraded my Gentoo system. I think it might be caused by newer version of Xorg server or i3.
## To Reproduce
Sleep the system and then wake it up.

See the attachment file for polybar configs.

## Polybar Log

Below is only the error log. See the attachment file for full log.
```
polybar|notice:  randr_screen_change_notify (2160x1440)... reloading
polybar|notice:  Termination signal received, shutting down...
polybar|warn:  module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
polybar|notice:  Parsing config file: /home/zypang/.config/polybar/config
polybar|error: No monitors found
```

## Environment:
* WM: i3-4.18 xorg-server-1.20.11
* Distro: Gentoo
* Output of `polybar -vvv`:

```
polybar 3.5.5

Features: +alsa -curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -pipe -Wall -Wextra -Wpedantic
Linker flags: -Wl,-O1 -Wl,--as-needed
```

## Additional context

[polybar-error.log](https://github.com/polybar/polybar/files/6390165/polybar-error.log)
[config.txt](https://github.com/polybar/polybar/files/6390173/config.txt)

### PR DESCRIPTION
**Pull request by farhaven**
## What type of PR is this? (check all applicable)

* [ ] Refactor
* [ ] Feature
* [X] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

On laptops and similar devices, RandR sometimes returns zero active screens, for example when closing a laptop's lid before it suspends.

Don't restart in that case because the new polybar instance will see zero screens and quit. Instead, just ignore those kind of events.

## Related Issues & Documents

Fixes #2418. 

## Documentation (check all applicable)

* [ ] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [X] Does not require documentation changes

### CODE REVIEW

File: src/components/screen.cpp [hunk 1]
```diff
@@ -107,7 +108,12 @@ void screen::handle(const evt::randr_screen_change_notify& evt) {
   if (screen->width_in_pixels != m_size.w || screen->height_in_pixels != m_size.h) {
     changed = true;
   } else {
-    changed = have_monitors_changed();
+    auto p = have_monitors_changed();
```
Comment (patrick96) [inline src/components/screen.cpp:111]: We should use structured binding here for clarity. Something like this:

```
    auto [changed, num_monitors] = have_monitors_changed();
```

Not sure how that behaves though since `changed` is already defined, so maybe something like this:

```
    int num_monitors = 0;
    std::tie(changed, num_monitors) = have_monitors_changed();
```

Or this:

```
    auto [changed_, num_monitors] = have_monitors_changed();
    changed = changed_
```

File: src/components/screen.cpp [hunk 2]
```diff
@@ -107,7 +108,12 @@ void screen::handle(const evt::randr_screen_change_notify& evt) {
...
+    changed = p.first;
+    if (p.second == 0) {
```
Comment (patrick96) [inline src/components/screen.cpp:113]: Might be worth moving this one level up, outside of the `else` block so that we also don't reload if the screen size changed *and* there are no monitors.

**Review by patrick96 — CHANGES_REQUESTED** [review]
Approach looks good.

Please also add an entry to the [changelog](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog) under a `Changed` header

File: src/components/screen.cpp (hunk 1 above)
Comment (farhaven) [reply src/components/screen.cpp:111]: I did not know about destructed binding. TIL :)

**Comment by farhaven** [comment]
Ping :)

**Comment by Hibbins** [comment]
Can we get this in? @patrick96

**Comment by h1divp** [comment]
Please.....

**Review by patrick96 — APPROVED** [review]
This one went under, sorry. Looks good now :)
