### PR TITLE
Restack refactoring

### LINKED ISSUE #2873: [Bug]: Workspaces not clickable on BSPWM
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Boot your computer with the internal laptop display off using `xrandr --output eDP --off` and the external display on and start polybar. The issue is then fixed after turning the internal display on and then off.

### Minimal config

```dosini
[colors]
focus-dark = #20232A
blue = #61afef
bg = #31353F
fg = #abb2bf

[bar/top]
monitor = "HDMI-A-0"
width = 100%
background = ${colors.bg}
foreground = ${colors.fg}
font-0 = "Hack Nerd Font Mono:pixelsize=19;4"
modules-left = bspwm
wm-restack = bspwm

[module/bspwm]
type = internal/bspwm
enable-click = true
ws-icon-default = %{T1}  %{T-}
label-focused = %icon%
label-focused-foreground = ${colors.focus-dark}
label-focused-background = ${colors.blue}
```

### Polybar log

```text
notice: Parsing config file: /home/eric/.config/polybar/config.ini
- config_parser: Parsing /home/eric/.config/polybar/config.ini
* Loaded monitor HDMI-A-0 (2560x1440+0+0)
* Configured DPI = 96x96
* Bar geometry: 2560x24+0+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Setup user-defined modules
notice: Loading module 'bspwm' of type 'internal/bspwm'
notice: Loaded 1 modules
* Starting application
- controller: Main thread id = 1
* Starting module/bspwm
* Entering event loop (thread-id=1)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- module/bspwm: Thread id = 2
* module/bspwm: Parsing socket data: MHDMI-A-0:o1:o2:f3:O4:f5:f6:f7:f8:f9:f10:LM:TT:G
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
notice: Loaded font "Hack Nerd Font Mono:pixelsize=19" (name=Hack Nerd Font Mono, offset=4, file=/usr/share/fonts/TTF/Hack Regular Nerd Font Complete Mono.ttf)
- Activate root background manager
- background_manager: root pixmap (0x2e00001:24) 2560x1440+0+0
- background_manager: Allocating pixmap
- background_manager: Allocating graphics context
- background_manager: Allocating cairo surface
- background_manager: Copying from root pixmap (0x2e00001:24) 2560x24+0+0
* Bar window: 0x5000001
- bar: Reconfigure window
* Successfully restacked bar window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- background_manager: update_geometry
- background_manager: root pixmap (0x2e00001:24) 2560x1440+0+0
- background_manager: Copying from root pixmap (0x2e00001:24) 2560x24+0+0
- bar: Draw empty bar
- bar: Setup tray manager
- background_manager: update_geometry
- background_manager: root pixmap (0x2e00001:24) 2560x1440+0+0
- background_manager: Copying from root pixmap (0x2e00001:24) 2560x24+0+0
- bar: Received expose event
* module/bspwm: Rebuilding cache
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=686x24+0+0, falloff=0)
```

### Expected behavior

BSPWM module should be clickable

### Actual behavior

Can't click desktops to switch between them. Only that module is unclickable.

### Window Manager and Version

BSPWM  0.9.10

### Linux Distribution

EndeavourOS

### Polybar version

```text
polybar 3.6.3-83-g10cdec3b

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

### Additional Context / Screenshots

_No response_

### PR DESCRIPTION
**Pull request by patrick96**
## What type of PR is this? (check all applicable)

* [x] Refactor
* [x] Feature
* [x] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

Refactors the restacking algorithms and adds new ones.

The restacking algorithms now only have to provide the sibling window and stacking mode.

**New strategies**

* `ewmh`: Tries to put the bar window above the _NET_SUPPORTING_WM_CHECK window
* `bottom`: Puts the bar window at the bottom of the window stack (same as the old generic strategy)

The generic strategy is now a best effort strategy which simply tries out other strategy until it finds a suitable one. Currently it first tries ewmh, then bottom.

Additionally, the `bspwm` strategy also first tries ewmh before falling back to searching for the dedicated root windows for each monitor.

## Related Issues & Documents

Fixes #2873

May also work for #2543

## Documentation (check all applicable)

* [x] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

Add the new strategies as well as the changes to the strategy to the wiki.
Also mention that generic is best-effort, it may change in the future, and all its component strategies are available on their own.

### CODE REVIEW

File: src/components/bar.cpp [hunk 1]
```diff
@@ -497,9 +498,7 @@ void bar::restack_window() {
     try {
       auto children = m_connection.query_tree(m_connection.root()).children();
       if (children.begin() != children.end() && *children.begin() != m_opts.x_data.window) {
-        const unsigned int value_mask = XCB_CONFIG_WINDOW_SIBLING | XCB_CONFIG_WINDOW_STACK_MODE;
-        const unsigned int value_list[2]{*children.begin(), XCB_STACK_MODE_BELOW};
-        m_connection.configure_window_checked(m_opts.x_data.window, value_mask, value_list);
+        restack_util::restack_relative(m_connection, m_opts.x_data.window, *children.begin(), XCB_STACK_MODE_BELOW);
```
Comment (andro404-MC) [inline src/components/bar.cpp]: Probably the cause of [https://github.com/polybar/polybar/issues/2972](url)
