### PR TITLE
Audio unmute on scroll

### LINKED ISSUE #3067: [Bug]: Pulseaudio volume increases on scroll when muted, but doesn't unmute
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Run `polybar -c config.ini`
2. Note the current volume (example: 20%)
3. Click on the pulseaudio module to mute
4. Scroll on the pulseaudio module to change the volume
5. Click on the pulseaudio module again to unmute

### Minimal config

```dosini
[bar/top]
width=100%
height=32pt
background="#000000"
foreground="#ffffff"

font-0 = "Monospace"

modules-left = pulseaudio

[module/pulseaudio]
type = internal/pulseaudio
label-muted = muted
label-muted-foreground = #666
```

### Polybar log

```text
polybar|notice:  Parsing config file: config.ini
polybar|warn:  No monitor specified, using "eDP-1-1"
polybar|notice:  Loading module 'pulseaudio' of type 'internal/pulseaudio'
polybar|notice:  pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
polybar|notice:  Loaded 1 modules
polybar|notice:  Loaded font "Monospace" (name=Noto Sans Mono, offset=0, file=/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf)
polybar|notice:  Received signal(2): Interrupt
polybar|notice:  Termination signal received, shutting down...
```

### Expected behavior

I expect the pulseaudio to unmute on scroll if volume is currently muted, similar to what `amixer -D pulse sset Master 5%+ unmute` would do

### Actual behavior

The volume increases but stays unmuted. If this is intended maybe an option such as `unmute-on-scroll` could be added for this

### Window Manager and Version

bspwm 0.9.10-51-gaf3bd8b

### Linux Distribution

Ubuntu 23.04 x86_64

### Polybar version

```text
polybar 3.7.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

### Additional Context / Screenshots

_No response_

### PR DESCRIPTION
**Pull request by roddyrap**
## What type of PR is this? (check all applicable)

* [ ] Refactor
* [X] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

Added the option `unmute-on-scroll` to the `alsa` and `pulseaudio` modules. If this option is false (The default) then there is no difference in behaviour from the previous version. If the option is true, when the user uses the scrollwheel on the module, the sound will be unmuted.

## Related Issues & Documents

Closes #3067

## Documentation (check all applicable)

* [X] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

It might be worth to mention this as an option in the wiki, so that folks could be aware of it.

### CODE REVIEW

File: include/modules/alsa.hpp [hunk 1]
```diff
@@ -67,6 +67,7 @@ namespace modules {
     map<control, control_t> m_ctrl;
     int m_headphoneid{0};
     bool m_mapped{false};
+    bool m_unmuteOnScroll{false};
```
Comment (patrick96) [inline include/modules/alsa.hpp:70]:
```suggestion
    bool m_unmute_on_scroll{false};
```

We're using snake_case for variable names, please also update in other module

File: CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 ## [Unreleased]
+### Added
+- An option `unmute-on-scroll` for `internal/pipewire` and `internal/alsa` to unmute audio when the user scrolls on the widget.
```
Comment (patrick96) [inline CHANGELOG.md:13]:
```suggestion
- An option `unmute-on-scroll` for `internal/pulseaudio` and `internal/alsa` to unmute audio when the user scrolls on the widget.
```

File: src/modules/alsa.cpp [hunk 3]
```diff
@@ -261,6 +262,7 @@ namespace modules {
     }
     const auto& mixers = get_mixers();
     for (auto&& mixer : mixers) {
+      mixer->set_mute(m_unmuteOnScroll || !mixer->is_muted());
```
Comment (patrick96) [inline src/modules/alsa.cpp:265]: Wouldn't this mute instead of unmute?

In any case, we should only call the `set_mute` method if `unmute-on-scroll` is enabled, to avoid the overhead of calling into the alsa library

File: src/modules/pulseaudio.cpp [hunk 4]
```diff
@@ -156,10 +157,12 @@ namespace modules {
   }
 
   void pulseaudio_module::action_inc() {
+    m_pulseaudio->set_mute(!m_unmuteOnScroll && m_muted);
```
Comment (patrick96) [inline src/modules/pulseaudio.cpp:160]: Same here. Just call `set_mute(false)` if the user enabled `unmute-on-scroll`

**Review by patrick96 — CHANGES_REQUESTED** [review]
Thanks!

Please also update the descriptions of the `inc` and `dec` [actions](https://polybar.readthedocs.io/en/stable/user/actions.html#internal-alsa) for the two modules to mention the `unmute-on-scroll`.

File: src/modules/alsa.cpp (hunk 3 above)
Comment (roddyrap) [reply src/modules/alsa.cpp:265]: I did check this before because it confused me as well, but no. Alsa's set_mute is inverted, meaning passing false makes it muted.
I verified (Before and after the incoming fixes) both modules on my computer, and muting and unmuting work correctly.

Comment (patrick96) [reply src/modules/alsa.cpp]: Well that's incredibly bad design on our part, we will have to fix that at some point
