### PR TITLE
fix(xworkspaces): Assign desktops to correct viewport

### LINKED ISSUE #1764: Dual monitors, module/xworkspaces, bspwm and pin-workspaces
## Describe the issue
**Expected behavior:**

My setup is 1080p monitor + 2160p Monitor/TV over HDMI, I use bspwm on Arch and polybar-git from the AUR, when I use the xworkspaces and set pin-workspaces to true, it doesn't show the workspaces on the right monitor, instead the xworkspace module on monitor 1 shows half of the WSs and the one on monitor 2 the rest

WS 1-11 on Monitor 1 as defined in my bspwmrc
WS 12 on Monitor 2 as defined in my bspwmrc

**Actual behavior:**

xworkspace module on monitor 1 shows WS 1-6
xworkspace module on monitor 2 shows WS 7-12

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true

enable-scroll = true

icon-0 = 一
icon-1 = 二
icon-2 = 三
icon-3 = 四
icon-4 = 五
icon-5 = 六
icon-6 = 七
icon-7 = 八
icon-8 = 九
icon-9 = 十
icon-10 = 十一
icon-11 = 〇
icon-default = 一

format = <label-state>
format-padding = 0

label-monitor = %name%

label-active = %name%
label-active-foreground = ${color.ac}
label-active-background = ${color.bg}
label-active-overline = ${color.ac}

label-occupied = %name%
label-occupied-underline = ${color.fg}

label-urgent = %name%
label-urgent-foreground = ${color.red}
label-urgent-background = ${color.bg}

label-empty = %name%
label-empty-foreground = ${color.fg}

label-active-padding = 2
label-urgent-padding = 2
label-occupied-padding = 2
label-empty-padding = 2
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
https://i.imgur.com/sTtaAJs.png
## Environment:
* WM: bspwm
* Distro: Arch
* Output of `polybar -vvv`:

polybar 3.3.0-85-g9103d232

Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 

Am I doing anything wrong is that a bug? It seems like on a multimonitor setup polybar/xworkspaces doesn't recognise which workspace belongs on what monitor and just assumes a 50:50 split

### LINKED ISSUE #1849: xworkspaces missing monitor
## Describe the issue
Some workspaces aren't displayed by polybar.

**Expected behavior:**

All workspaces should be displayed.

**Actual behavior:**

Some workspaces aren't displayed.

* Did you also experience this bug in an earlier version of polybar? Yes
* If no, what was the last version where this worked correctly? Don't know

## To Reproduce
Config:
```dosini
[bar/example]
modules-center = ewmh

[module/ewmh]
type = internal/xworkspaces

```
xrandr output:
```
Screen 0: minimum 8 x 8, current 5360 x 1440, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 380mm x 210mm
   1920x1080     60.04*+  59.93  
   [...]
DP1 connected 3440x1440+1920+0 (normal left inverted right x axis y axis) 800mm x 330mm
   3440x1440     59.97 +  74.98*
   [...]
```

Open one workspace on the left screen.
Open two workspaces on the right screen.
The last one isn't displayed.

## Polybar Log
Nothing relevant in logs.

## Screenshots

polybar

## Environment:
* WM: i3-gaps version 4.16.1
* Distro: Linux 5.2.5-arch1-1-ARCH x86_64 GNU/Linux
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
The problem comes from this code block:
https://github.com/polybar/polybar/blob/58d72c4f1939ae1af4e853c19b9e1cd1be3de8db/src/modules/xworkspaces.cpp#L168-L173

In my example I have three workspaces, `bounds.size()=3` and `m_desktop_names.size()=3` so `step=1` then when we enter into the following loop, there is only one workspace registered for each viewport.
https://github.com/polybar/polybar/blob/58d72c4f1939ae1af4e853c19b9e1cd1be3de8db/src/modules/xworkspaces.cpp#L198-L200

### PR DESCRIPTION
**Pull request by patrick96**
Before the module would just try to evenly distribute desktops
(workspaces) among the viewports.

But since `_NET_DESKTOP_VIEWPORT` actually maps desktops to viewports,
we can use that information to assign workspaces to the right viewport.

I wasn't able to test this yet since I don't have access to my multimonitor setup right now.

Fixes #1849
Fixes #1764

### CODE REVIEW

File: src/modules/xworkspaces.cpp [hunk 1]
```diff
@@ -20,6 +20,15 @@ namespace {
   }
 }  // namespace
 
+/**
+ * Defines a lexicographical order on position:
+ *
+ * (x1, y1) < (x2, y2) <==> (x1 == x2 && y1 < y2) || (x1 < x2)
+ */
+bool operator<(const position& a, const position& b) {
+  return a.x < b.x || (a.x == b.x && a.y < b.y);
```
Comment (Lomadriel) [inline src/modules/xworkspaces.cpp]: For this case this might be overkill but if you want to do that for a struct that have a lot of attributes.

```suggestion
  return std::make_tuple(a.x, a.y) < std::make_tuple(b.x, b.y);
```

**Comment by patrick96** [comment]
I'm unable to reproduce this, what program are you using to arrange your screens?

Also, what does `xprop -root` give you and what does polybar display?

**Comment by Lomadriel** [comment]
I use `arandr`. It doesn't seem to be a bug into your code.
i3wm doesn't seem to update the property.

Before creating a new desktop.
```
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 1080, 0, 1080, 0, 1080, 0, 1080, 0, 1080
```

After:
```
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 1920, 0, 1920, 0, 1920, 0, 1920, 0, 1920, 0
```

I'll try to investigate that and if I'll see if this is a `arandr` bug or a `i3wm` one.

**Comment by patrick96** [comment]
Yeah, seems like an i3 issue as well. Looks like they don't immediately adjust once the monitor setup changes.

**Comment by patrick96** [comment]
I have filed a report over in the i3 repository: https://github.com/i3/i3/issues/4053

This seems to me indeed like an i3 bug.
